name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: keycasty
          # the following are defaults on github actions
          # description: ""
          # pandoc: "README.md"
          toc: false
          version: "Vim v8.2.3995+ or NeoVim v0.6.1+"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto generate docs'
          branch: ${{ github.head_ref }}
